sonar.projectKey=easytransit
sonar.projectName=EasyTransit
sonar.projectVersion=1.0

sonar.sources=core,transport_system
sonar.exclusions=**/migrations/**,**/venv/**,**/__pycache__/**,**/static/**,**/templates/**

sonar.host.url=http://localhost:9000
sonar.token=sqa_2894b48ff0c3148344d60a789ce9e014eae5fe14

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

