# Generated by Django 5.2 on 2025-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('passenger', 'Passenger'), ('DRIVER', 'Driver')], max_length=20),
        ),
    ]
