# Generated by Django 5.2 on 2026-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('PASSENGER', 'Passenger'), ('DRIVER', 'Driver')], default='PASSENGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
