# Generated by Django 5.2 on 2026-05-27 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bus_bus_number_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('found', 'Found'), ('returned', 'Returned'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(limit_choices_to={'role': 'PASSENGER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip')),
            ],
        ),
    ]
